dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
# Add-ons: specify apt packages for Linux
addons:
  apt:
   update: true
   packages:
     - python-openimageio
     - cmake
     - ffmpeg
     - make
   sources:
     - ubuntu-toolchain-r-test
     
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install python-openimageio -y

script:
  - ./runtests
