dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
# Add-ons: specify apt packages for Linux
addons:
  apt:
    update: true
   sources:
     - ubuntu-toolchain-r-test
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/+files/ffmpeg_3.3.3~trusty2_amd64.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i ffmpeg_3.3.3~trusty2_amd64.deb ; fi
script:
  - ./runtests
