dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true

# Add-ons: specify apt packages for Linux
before_install:
  - sudo add-apt-repository ppa:mc3man/bionic-media -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update --allow-unauthenticated
  - sudo apt-get install python-openimageio -y
  - sudo apt-get install openimageio-tools -y
  - sudo apt-get install cmake -y
  - sudo apt-get install ffmpeg-static -y
  - sudo apt-get install make -y
     
script:
  - ./runtests
