dist: bionic
language: python
install:
  - pip install pylama
python:
  - "2.7"
virtualenv:
  system_site_packages: true

# Add-ons: specify apt packages for Linux
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install python-openimageio -y
  - sudo apt-get install openimageio-tools -y
  - sudo apt-get install cmake -y
  - sudo apt-get install ffmpeg -y
  - sudo apt-get install make -y
  - wget -qO- https://github.com/GafferHQ/gaffer/releases/download/0.53.1.1/gaffer-0.53.1.1-linux.tar.gz | tar xvz -
  - export PATH="gaffer-0.53.1.1-linux/bin:$PATH"
     
script:
  - ./runtests
  - ./runlint
