dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
# Add-ons: specify apt packages for Linux
addons:
  apt:
   update: true
   packages:
     - python-openimageio
     - cmake
     - ffmpeg
     - make
   sources:
     - ubuntu-toolchain-r-test
script:
  - ./runtests
